theme: minima
title: Histwo
author: the Creator's two servants
description: "Histwo is the official website of the Creator’s two servants, eternal instruments of His will, incarnated to protect His creation."
baseurl: "/"
url: "https://Histwo.github.io"
github_username: Histwo
header_pages:
  - about.md
  - TAG.md
  - DC.md
  - lostOne.md
collections:
  faqs:
    output: true
    defaults:
      - scope:
          path: ""
          type: faqs
        values:
          layout: faq

