theme: minima
title: Histwo
author: the Creator's two servants
description: "Histwo is the official website of the Creator’s two servants.<br> His two servants.<br>Instruments of His will.<br>Incarnated for His purposes.<br>"
baseurl: "/"
url: "https://Histwo.github.io"
github_username: Histwo
header_pages:
  - about.md
  - TAG.md
  - DC.md
  - lostOne.md
collections:
  FAQs:
    output: true
    permalink: /FAQs/:name/
  insights:
    output: true
    permalink: /arts/:name/
defaults:
  - scope:
      path: ""
      type: "FAQs"
    values:
      layout: "faqs"
  - scope:
      path: ""
      type: "insights"
    values:
      layout: "arts"
